name: Prueba num 1 (Flask)

on:
  push:
    branches:
      - main

jobs:
  decir-hola:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: produccion
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Logearnos en GHCR
        run: echo "${{ secrets.TOKEN1 }}" | docker login ghcr.io -u gosti21 --password-stdin

      - name: Crear imagen
        run: docker build . -t ghcr.io/gosti21/flask-image:latest

      - name: Desplegar imagen
        run: docker push ghcr.io/gosti21/flask-image:latest